{
 "title": "Airflow cluster dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "airflow_id", "label": "Airflow Instance Id", "query": "label_values(airflow_id)" }
  ]
 },
 "panels": [
  { "title": "Scheduler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Scheduler heartbeat / min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(airflow_scheduler_heartbeat[2m])",
     "legendFormat": "{{airflow_id}}"
    }
   ]
  },
  {
   "title": "Scheduler tasks running",
   "type": "graph",
   "description": "This metric is not present in the current version of docs. May not work properly",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "airflow_scheduler_tasks_running{airflow_id=\"$airflow_id\"}",
     "legendFormat": "{{airflow_id}}"
    }
   ]
  },
  {
   "title": "Scheduler pool open slots",
   "type": "stat",
   "description": "Number of open slots in the pool",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airflow_pool_open_slots{airflow_id=\"$airflow_id\"}",
     "legendFormat": "{{pool_name}}"
    }
   ]
  },
  {
   "title": "Dagbag size",
   "type": "stat",
   "description": "DAG bag size",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "airflow_dagbag_size{airflow_id=\"$airflow_id\"}"
    }
   ]
  },
  {
   "title": "Scheduler pool used slots",
   "type": "stat",
   "description": "Number of used slots in the pool",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airflow_pool_used_slots{airflow_id=\"$airflow_id\"}",
     "legendFormat": "{{pool_name}}"
    }
   ]
  },
  {
   "title": "Scheduler pool starving tasks",
   "type": "stat",
   "description": "Number of starving tasks in the pool",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airflow_pool_starving_tasks{airflow_id=\"$airflow_id\"}",
     "legendFormat": "{{pool_name}}"
    }
   ]
  },
  {
   "title": "Scheduler tasks pending",
   "type": "graph",
   "description": "This metric is not present in the current version of docs. May not work properly",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "airflow_scheduler_tasks_pending{airflow_id=\"$airflow_id\"}",
     "legendFormat": "{{airflow_id}}"
    }
   ]
  },
  {
   "title": "Scheduler tasks starving",
   "type": "graph",
   "description": "This metric is not present in the current version of docs. May not work properly",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "airflow_scheduler_tasks_starving{airflow_id=\"$airflow_id\"}",
     "legendFormat": "{{airflow_id}}"
    }
   ]
  },
  {
   "title": "DAG processing processor timeouts",
   "type": "stat",
   "description": "Number of file processors that have been killed due to taking too long",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "airflow_dag_processing_processor_timeouts{airflow_id=\"$airflow_id\"}"
    }
   ]
  },
  {
   "title": "Dagbag import errors",
   "type": "stat",
   "description": "Number of errors from trying to parse DAG files",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "airflow_dag_processing_import_errors{airflow_id=\"$airflow_id\"}"
    }
   ]
  },
  {
   "title": "Scheduler tasks executable",
   "type": "graph",
   "description": "This metric is not present in the current version of docs. May not work properly",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "airflow_scheduler_tasks_executable{airflow_id=\"$airflow_id\"}",
     "legendFormat": "{{airflow_id}}"
    }
   ]
  },
  {
   "title": "DAG processing total parse time",
   "type": "graph",
   "description": "Seconds taken to scan and import all DAG files once",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "airflow_dag_processing_total_parse_time{airflow_id=\"$airflow_id\"}",
     "legendFormat": "{{airflow_id}}"
    }
   ]
  },
  {
   "title": "Zombies killed",
   "type": "stat",
   "description": "Zombie tasks killed",
   "gridPos": { "h": 4, "w": 5, "x": 18, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airflow_zombies_killed{airflow_id=\"$airflow_id\"}"
    }
   ]
  },
  {
   "title": "Tasks killed externally",
   "type": "stat",
   "description": "Tasks killed externally",
   "gridPos": { "h": 4, "w": 5, "x": 18, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airflow_scheduler_tasks_killed_externally{airflow_id=\"$airflow_id\"}"
    }
   ]
  },
  {
   "title": "Tasks success rate / min",
   "type": "graph",
   "description": "Total success tasks / min",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(airflow_ti_successes{airflow_id=\"$airflow_id\"}[2m]) * 60",
     "legendFormat": "{{airflow_id}}"
    }
   ]
  },
  {
   "title": "Tasks failure rate / min",
   "type": "graph",
   "description": "Total failure tasks / min",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(airflow_ti_failures{airflow_id=\"$airflow_id\"}[2m]) * 60",
     "legendFormat": "{{airflow_id}}"
    }
   ]
  },
  {
   "title": "Operator success rate / min",
   "type": "graph",
   "description": "Operator success rate / min",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short", "label": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(airflow_operator_successes{airflow_id=\"$airflow_id\"}[2m]) * 60",
     "legendFormat": "{{operator_name}}"
    }
   ]
  },
  {
   "title": "Operator failure rate / min",
   "type": "graph",
   "description": "Operator failure rate / min",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 29 },
   "yaxes": [
    { "format": "short", "label": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(airflow_operator_failures{airflow_id=\"$airflow_id\"}[2m]) * 60",
     "legendFormat": "{{operator_name}}"
    }
   ]
  },
  { "title": "Executor Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Jobs started per minute",
   "type": "graph",
   "description": "Number of started <job_name> job, ex. SchedulerJob, LocalTaskJob",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(airflow_job_start{airflow_id=\"$airflow_id\"}[2m]) * 60",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "Executor open slots",
   "type": "stat",
   "description": "Due to dynamic nature of KubernetesExecutor, this metric might not be useful",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airflow_executor_open_slots{airflow_id=\"$airflow_id\"}"
    }
   ]
  },
  {
   "title": "Executor queued tasks",
   "type": "stat",
   "description": "Due to dynamic nature of KubernetesExecutor, this metric might not be useful",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airflow_executor_queued_tasks{airflow_id=\"$airflow_id\"}"
    }
   ]
  },
  {
   "title": "Jobs ended per minute",
   "type": "graph",
   "description": "Number of ended <job_name> job, ex. SchedulerJob, LocalTaskJob",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(airflow_job_end{airflow_id=\"$airflow_id\"}[2m]) * 60",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "Executor running tasks",
   "type": "stat",
   "description": "Due to dynamic nature of KubernetesExecutor, this metric might not be useful",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airflow_executor_running_tasks{airflow_id=\"$airflow_id\"}"
    }
   ]
  },
  { "title": "DAG stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Success DAG run duration",
   "type": "graph",
   "description": "Seconds taken for a DagRun to reach success state",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "airflow_dagrun_duration_success{airflow_id=\"$airflow_id\"} * 1000",
     "legendFormat": "{{dag_id}} p{{quantile}}"
    }
   ]
  },
  {
   "title": "Failed DAG run duration",
   "type": "graph",
   "description": "Seconds taken for a DagRun to reach failed state",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "airflow_dagrun_duration_failed{airflow_id=\"$airflow_id\"} * 1000",
     "legendFormat": "{{dag_id}} p{{quantile}}"
    }
   ]
  },
  {
   "title": "DAG run duration",
   "type": "graph",
   "description": "Sum of seconds taken to finish a tasks aggregated by DAG",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (dag_id, quantile) (airflow_dag_task_duration{airflow_id=\"$airflow_id\"}) * 1000",
     "legendFormat": "{{dag_id}} p{{quantile}}"
    }
   ]
  },
  {
   "title": "DAG run dependency check time",
   "type": "graph",
   "description": "Seconds taken to check DAG dependencies",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "airflow_dagrun_dependency_check{airflow_id=\"$airflow_id\"} * 1000",
     "legendFormat": "{{dag_id}} p{{quantile}}"
    }
   ]
  },
  {
   "title": "DAG run schedule delay",
   "type": "graph",
   "description": "Seconds of delay between the scheduled DagRun start date and the actual DagRun start date",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "airflow_dagrun_schedule_delay{airflow_id=\"$airflow_id\"} * 1000",
     "legendFormat": "{{dag_id}} p{{quantile}}"
    }
   ]
  },
  {
   "title": "DAG loading duration",
   "type": "graph",
   "description": "Metrics not documented in the current version of docs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "airflow_dag_loading_duration{airflow_id=\"$airflow_id\"} * 1000",
     "legendFormat": "{{dag_id}} p{{quantile}}"
    }
   ]
  },
  { "title": "DAG file stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "title": "DAG file last runtime",
   "type": "graph",
   "description": "Seconds spent processing <dag_file> (in most recent iteration)",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "airflow_dag_processing_last_runtime{airflow_id=\"$airflow_id\"} * 1000",
     "legendFormat": "{{dag_file}} p{{quantile}}"
    }
   ]
  },
  {
   "title": "DAG file processing last load time",
   "type": "graph",
   "description": "Seconds taken to load the given DAG file",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "airflow_dag_processing_last_duration{airflow_id=\"$airflow_id\"} * 1000",
     "legendFormat": "{{dag_file}} p{{quantile}}"
    }
   ]
  },
  {
   "title": "DAG file processing last run seconds",
   "type": "graph",
   "description": "Seconds since <dag_file> was last processed",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "airflow_dag_processing_last_run_seconds{airflow_id=\"$airflow_id\"}",
     "legendFormat": "{{dag_file}} p{{quantile}}"
    }
   ]
  }
 ]
}